---
- name: "Instala pacotes de dependência do sistema operacional"
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - mysql-server-5.6
    - python-mysqldb

- name: "cria o banco do MySQL"
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: "{{ wp_user_root }}"
    state: present

- name: "Cria o usuário do MySQL"
  mysql_user:
    login_user: "{{ wp_user_root }}"
    name: "{{ wp_username }}"
    password: { { wp_user_password } }
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}" 
  with_items:
    - "{{ wp_db_ip }}"
